### PR TITLE
Cleanup Scala code

### PR DESCRIPTION
**Pull request by YikSanChan**
**What this PR does / why we need it**:

Cleanup Scala code.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by YikSanChan** [comment]
@woop Shall I resolve the conflict so that someone can take a look?

**Comment by woop** [comment]
> @woop Shall I resolve the conflict so that someone can take a look?

Hey @YikSanChan. I am not the right person to approve these commits. @pyalex would be better positioned. Since there has been no movement here, would you mind also asking him directly in Slack?

**Comment by YikSanChan** [comment]
@pyalex All tests pass, do you mind taking another look? Thanks

**Comment by YikSanChan** [comment]
@woop The test test-end-to-end-azure-presubmit looks unrelated but it fails multiple times, could you please help with a look?

**Comment by woop** [comment]
> @woop The test test-end-to-end-azure-presubmit looks unrelated but it fails multiple times, could you please help with a look?

That test is not related to your code I believe.

**Comment by YikSanChan** [comment]
@woop Yah I think so

**Review by pyalex — APPROVED** [review]

**Pull request merged**
